image: python:3.8-slim-buster

stages:
  - build
  - test

build:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install requirements

test:
  stage: test
  script:
    - python src/test.py

