image: python:3.8-slim-buster

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install flask
    - python src/test.py